### ISSUE TITLE
Incorrect docs link

### ISSUE THREAD

**Issue by MysteryBlokHed** [Miksus/red-mail#3]
**Describe the bug**
Incorrect docs link on the repo. Links to <https://red-engine.readthedocs.io/en/latest/> instead of <https://red-mail.readthedocs.io/en/latest/>.

**Screenshots**
![Screenshot of page](https://user-images.githubusercontent.com/13910387/147867546-1681db0c-f795-4600-9ba8-0fa1b4d278ce.png)

**Comment by Miksus** [comment]
Thank you for pointing this out, fixed. 

Perhaps I named these two projects a bit too similarly.
