### ISSUE TITLE
BUG: E-Mails aren't being sent, no error messages etc

### ISSUE THREAD

**Issue by tarik56** [Miksus/red-mail#34]
```
email = EmailSender(
        host=config.smtp_server,
        port=config.smtp_port,
        user_name=config.smtp_user,
        password=config.smtp_pass
)
email.send(
    subject="My Subject",
    sender=config.smtp_user,
    receivers=["myemail@email.com"],
    text="Test"
)
```
Is not doing anything, emai is not receiving anything and there are also no messages. The only Error I get after like 3-5 minutes is the following:
```
raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

Can anyone validate that the latest version does indeed work with a simple example as above.

The same credentials work with the standard python smtp code with no issues eg.

```
server = smtplib.SMTP_SSL(config.smtp_server, config.smtp_port, context=ssl.create_default_context())
server.login(config.smtp_user, config.smtp_pass)
message = MIMEMultipart("alternative")
message["Subject"] = "Subject"
message["From"] = config.smtp_user
message["To"] = recipient
```

**Comment by Miksus** [comment]
Sorry for taking way too long to look into this. I think I had a quick glance at this and completely forgot to reply. 

I think the difference is the SMTP instance which is not used in the Red Mail version. You may use the same by:
```python
email = EmailSender(
        host=config.smtp_server,
        port=config.smtp_port,
        user_name=config.smtp_user,
        password=config.smtp_pass,
   
        # Define the Server
        cls_smtp=smtplib.SMTP_SSL,
        kws_smtp={"context": ssl.create_default_context()},
        use_starttls=False
)

# Then send the email
email.send(
    subject="My Subject",
    sender=config.smtp_user,
    receivers=["myemail@email.com"],
    text="Test"
)
```
By default, ``use_starttls`` is True as that's most often wanted with SMTP. You may also override the method ``get_server`` and return a server instance (like instance of the ``SMTP_SSL``) if you wish to create it yourself.

More about setupping the client: https://red-mail.readthedocs.io/en/latest/tutorials/client.html

**Comment by Miksus** [comment]
Say if this does (or did) solve your issue, or if this should be reopened.
