### ISSUE TITLE
BUG: Emails with templates do not attach files correctly

### ISSUE THREAD

**Issue by Godlance** [Miksus/red-mail#37]
First of all, thank you for this life-saving library: Easy templating has been a total game-changer.

**Describe the bug**
When using Jinja templates, attached files are not correctly attached to the email, as the message Content-Type is set to multipart/alternative instead of multipart/mixed. 

Attachments are treated by mail clients as embedded content and thus not shown or recognized as attachments.

**To Reproduce**

1.- Create a simple snippet that includes both a template and an attachment (in any form):

```
redmail.send(
                subject='[%s] Email data for %s' % (str(instance),str(mail_id)),
                receivers=[str(email_address)],
                html_template='jinja_template.html',
                attachments=str(os.path.join(temp_path, str(attachment_filename))),
                body_params={'json_data': json_data,},
                body_images={
                    'logo': '/tmp/ogo.png',
                },
            )
```

**Expected behavior**
The mail is shown in the email client with the attachment.

Instead, the attachment is in the mail's source code but not available to download from the client.

**Email provider:**
 - Email service: private postfix
 - Application to view the email: Thunderbird, Gmail Client

**Environment (please complete the following information if relevant):**
 - OS: Linux
 - Python version: 3.8
 - Red Mail version: 0.3.1

**Additional context**

It is possible to fix this issue temporalily by modifying the 'attach' method from attachment.py to always set the message as mixed:

```
def attach(self, msg:EmailMessage):
        if msg.get_content_type() == "text/plain":
            # We need to change the content type
            # This occurs if no body is defined or only text is defined
            # The content type is therefore changed to multipart/mixed
            # See issue #23
            msg.make_mixed()
        else:
            try:
                msg.make_mixed()
            except Exception:
                pass
        for part in self._get_parts():
            msg.attach(part)
```

**Comment by Miksus** [comment]
Thanks and thanks for reporting this! I had tedious struggles with the content-types some time ago though (related to just that piece of code you posted) and those are not really pleasant to work with. 

How was your template? I tested with Windows, Python 3.8 and also Red Mail version 0.3.1 but for me the image is displaying correctly and the attachment is shown as an attachment.

My piece of code:

```python
msg = email.send(
    sender=...,
    receivers=...,
    subject="An attachment with image and attachment",
    html="<h1>This contains an attachment and image.</h1>{{ path_image }}",
    body_images={
        "path_image": Path(__file__).parent.parent / "docs/imgs/email_emb_img.png",
    },
    attachments={"a_file.html": (Path(__file__).parent / "file.html")}
)
```

Looks like this in Gmail (and shown correctly on Outlook):
![image](https://user-images.githubusercontent.com/37690409/158270285-775e33b9-2d7c-4005-b359-1c8182c065d9.png)

I'll test this with Linux in the upcoming days. I suspect the template should not be an issue as it should be rendered pretty much the same regardless if it comes from file or directly passed. The body_params neither sounds like an issue as I think it should be sanitized in terms of HTML by Jinja.

But I think there is things to improve anyways. I found [this SO post](https://stackoverflow.com/a/23853079/13696660) which implies it may be best to have the top part as mixed if possible. I'll investigate this.
