### ISSUE TITLE
BUG: Date header missing

### ISSUE THREAD

**Issue by PierrePetit** [Miksus/red-mail#67]
Hello,

I stumbled upon an issue using my ISP's SMTP server (Orange, a french ISP). By default, they don't add the email's "Date" header if it's missing, and it's considered a required field by their servers.

**Reproduction steps**
Create an orange email address at :
https://login.orange.fr/signup/identity
Send an email using Redmail with the ISP's default SMTP server :
smtp.orange.fr (port 587)

**Error**
Every time, I get this kind of error email :

![image](https://user-images.githubusercontent.com/4937633/209699782-d6948a78-cf1a-4391-ae95-8f78f49eecb5.png)

**Additional info**
Redmail version : 0.4.2
Python version : 3.8

I can PM the error email if needed.

I can send emails fine through their web client and using python's "email" package if I set the date using this :
```
[...]
from email.mime.multipart import MIMEMultipart
msg = MIMEMultipart('alternative')
msg['Date'] = utils.formatdate(localtime=True)
```

I believe the date field can be added in the "_create_body" function in "sender.py".
Maybe add a boolean parameter to allow adding the date, set to false by default, just in case it breaks something for someone else ?

I'm unsure if this should be a feature request or a bug, but since it's an error I can't get around using this library, I created a bug. If it needs to be a feature request, let me know.

Thanks for any help !

**Comment by Miksus** [comment]
Thanks for reporting this! This is now fixed in Redmail v0.5.0. The new version also includes ``Message-ID`` header which seems to be relevant for gmail nowadays and the new version also allows you to customize/pass own headers using the ``header`` attribute/argument.
